from setuptools import setup

setup(
    name='ML2018',
    version='0.1',
    packages=['venv.lib.python3.6.site-packages.h2', 'venv.lib.python3.6.site-packages.dns',
              'venv.lib.python3.6.site-packages.dns.rdtypes', 'venv.lib.python3.6.site-packages.dns.rdtypes.IN',
              'venv.lib.python3.6.site-packages.dns.rdtypes.ANY', 'venv.lib.python3.6.site-packages.pip',
              'venv.lib.python3.6.site-packages.pip._vendor', 'venv.lib.python3.6.site-packages.pip._vendor.idna',
              'venv.lib.python3.6.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.6.site-packages.pip._vendor.certifi',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip._internal', 'venv.lib.python3.6.site-packages.pip._internal.req',
              'venv.lib.python3.6.site-packages.pip._internal.vcs',
              'venv.lib.python3.6.site-packages.pip._internal.utils',
              'venv.lib.python3.6.site-packages.pip._internal.models',
              'venv.lib.python3.6.site-packages.pip._internal.commands',
              'venv.lib.python3.6.site-packages.pip._internal.operations', 'venv.lib.python3.6.site-packages.bson',
              'venv.lib.python3.6.site-packages.grpc', 'venv.lib.python3.6.site-packages.grpc.beta',
              'venv.lib.python3.6.site-packages.grpc._cython', 'venv.lib.python3.6.site-packages.grpc._cython._cygrpc',
              'venv.lib.python3.6.site-packages.grpc.framework',
              'venv.lib.python3.6.site-packages.grpc.framework.common',
              'venv.lib.python3.6.site-packages.grpc.framework.foundation',
              'venv.lib.python3.6.site-packages.grpc.framework.interfaces',
              'venv.lib.python3.6.site-packages.grpc.framework.interfaces.base',
              'venv.lib.python3.6.site-packages.grpc.framework.interfaces.face',
              'venv.lib.python3.6.site-packages.grpc.experimental', 'venv.lib.python3.6.site-packages.idna',
              'venv.lib.python3.6.site-packages.nltk', 'venv.lib.python3.6.site-packages.nltk.app',
              'venv.lib.python3.6.site-packages.nltk.ccg', 'venv.lib.python3.6.site-packages.nltk.sem',
              'venv.lib.python3.6.site-packages.nltk.tag', 'venv.lib.python3.6.site-packages.nltk.tbl',
              'venv.lib.python3.6.site-packages.nltk.chat', 'venv.lib.python3.6.site-packages.nltk.draw',
              'venv.lib.python3.6.site-packages.nltk.misc', 'venv.lib.python3.6.site-packages.nltk.stem',
              'venv.lib.python3.6.site-packages.nltk.test', 'venv.lib.python3.6.site-packages.nltk.test.unit',
              'venv.lib.python3.6.site-packages.nltk.test.unit.translate',
              'venv.lib.python3.6.site-packages.nltk.chunk', 'venv.lib.python3.6.site-packages.nltk.parse',
              'venv.lib.python3.6.site-packages.nltk.corpus', 'venv.lib.python3.6.site-packages.nltk.corpus.reader',
              'venv.lib.python3.6.site-packages.nltk.cluster', 'venv.lib.python3.6.site-packages.nltk.metrics',
              'venv.lib.python3.6.site-packages.nltk.twitter', 'venv.lib.python3.6.site-packages.nltk.classify',
              'venv.lib.python3.6.site-packages.nltk.tokenize', 'venv.lib.python3.6.site-packages.nltk.inference',
              'venv.lib.python3.6.site-packages.nltk.sentiment', 'venv.lib.python3.6.site-packages.nltk.translate',
              'venv.lib.python3.6.site-packages.past', 'venv.lib.python3.6.site-packages.past.tests',
              'venv.lib.python3.6.site-packages.past.types', 'venv.lib.python3.6.site-packages.past.utils',
              'venv.lib.python3.6.site-packages.past.builtins', 'venv.lib.python3.6.site-packages.past.translation',
              'venv.lib.python3.6.site-packages.pytz', 'venv.lib.python3.6.site-packages.tqdm',
              'venv.lib.python3.6.site-packages.tqdm.autonotebook', 'venv.lib.python3.6.site-packages.emoji',
              'venv.lib.python3.6.site-packages.hpack', 'venv.lib.python3.6.site-packages.hyper',
              'venv.lib.python3.6.site-packages.hyper.common', 'venv.lib.python3.6.site-packages.hyper.http11',
              'venv.lib.python3.6.site-packages.hyper.http20', 'venv.lib.python3.6.site-packages.hyper.packages',
              'venv.lib.python3.6.site-packages.hyper.packages.hpack',
              'venv.lib.python3.6.site-packages.hyper.packages.rfc3986',
              'venv.lib.python3.6.site-packages.hyper.packages.hyperframe', 'venv.lib.python3.6.site-packages.numpy',
              'venv.lib.python3.6.site-packages.numpy.ma', 'venv.lib.python3.6.site-packages.numpy.ma.tests',
              'venv.lib.python3.6.site-packages.numpy.doc', 'venv.lib.python3.6.site-packages.numpy.fft',
              'venv.lib.python3.6.site-packages.numpy.fft.tests', 'venv.lib.python3.6.site-packages.numpy.lib',
              'venv.lib.python3.6.site-packages.numpy.lib.tests', 'venv.lib.python3.6.site-packages.numpy.core',
              'venv.lib.python3.6.site-packages.numpy.core.tests', 'venv.lib.python3.6.site-packages.numpy.f2py',
              'venv.lib.python3.6.site-packages.numpy.f2py.tests', 'venv.lib.python3.6.site-packages.numpy.tests',
              'venv.lib.python3.6.site-packages.numpy.compat', 'venv.lib.python3.6.site-packages.numpy.compat.tests',
              'venv.lib.python3.6.site-packages.numpy.linalg', 'venv.lib.python3.6.site-packages.numpy.linalg.tests',
              'venv.lib.python3.6.site-packages.numpy.random', 'venv.lib.python3.6.site-packages.numpy.random.tests',
              'venv.lib.python3.6.site-packages.numpy.testing', 'venv.lib.python3.6.site-packages.numpy.testing.tests',
              'venv.lib.python3.6.site-packages.numpy.testing._private',
              'venv.lib.python3.6.site-packages.numpy.distutils',
              'venv.lib.python3.6.site-packages.numpy.distutils.tests',
              'venv.lib.python3.6.site-packages.numpy.distutils.command',
              'venv.lib.python3.6.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.6.site-packages.numpy.matrixlib',
              'venv.lib.python3.6.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.6.site-packages.numpy.polynomial',
              'venv.lib.python3.6.site-packages.numpy.polynomial.tests', 'venv.lib.python3.6.site-packages.scipy',
              'venv.lib.python3.6.site-packages.scipy.io', 'venv.lib.python3.6.site-packages.scipy.io.arff',
              'venv.lib.python3.6.site-packages.scipy.io.arff.tests', 'venv.lib.python3.6.site-packages.scipy.io.tests',
              'venv.lib.python3.6.site-packages.scipy.io.matlab',
              'venv.lib.python3.6.site-packages.scipy.io.matlab.tests',
              'venv.lib.python3.6.site-packages.scipy.io.harwell_boeing',
              'venv.lib.python3.6.site-packages.scipy.io.harwell_boeing.tests',
              'venv.lib.python3.6.site-packages.scipy.odr', 'venv.lib.python3.6.site-packages.scipy.odr.tests',
              'venv.lib.python3.6.site-packages.scipy._lib', 'venv.lib.python3.6.site-packages.scipy._lib.tests',
              'venv.lib.python3.6.site-packages.scipy.misc', 'venv.lib.python3.6.site-packages.scipy.misc.tests',
              'venv.lib.python3.6.site-packages.scipy.stats', 'venv.lib.python3.6.site-packages.scipy.stats.tests',
              'venv.lib.python3.6.site-packages.scipy.linalg', 'venv.lib.python3.6.site-packages.scipy.linalg.tests',
              'venv.lib.python3.6.site-packages.scipy.signal', 'venv.lib.python3.6.site-packages.scipy.signal.tests',
              'venv.lib.python3.6.site-packages.scipy.signal.windows', 'venv.lib.python3.6.site-packages.scipy.sparse',
              'venv.lib.python3.6.site-packages.scipy.sparse.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.isolve',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.isolve.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.csgraph',
              'venv.lib.python3.6.site-packages.scipy.sparse.csgraph.tests',
              'venv.lib.python3.6.site-packages.scipy.cluster', 'venv.lib.python3.6.site-packages.scipy.cluster.tests',
              'venv.lib.python3.6.site-packages.scipy.fftpack', 'venv.lib.python3.6.site-packages.scipy.fftpack.tests',
              'venv.lib.python3.6.site-packages.scipy.ndimage', 'venv.lib.python3.6.site-packages.scipy.ndimage.tests',
              'venv.lib.python3.6.site-packages.scipy.spatial', 'venv.lib.python3.6.site-packages.scipy.spatial.tests',
              'venv.lib.python3.6.site-packages.scipy.special', 'venv.lib.python3.6.site-packages.scipy.special.tests',
              'venv.lib.python3.6.site-packages.scipy.special._precompute',
              'venv.lib.python3.6.site-packages.scipy.optimize', 'venv.lib.python3.6.site-packages.scipy.optimize._lsq',
              'venv.lib.python3.6.site-packages.scipy.optimize.tests',
              'venv.lib.python3.6.site-packages.scipy.optimize._trlib',
              'venv.lib.python3.6.site-packages.scipy.optimize._trustregion_constr',
              'venv.lib.python3.6.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.lib.python3.6.site-packages.scipy.constants',
              'venv.lib.python3.6.site-packages.scipy.constants.tests',
              'venv.lib.python3.6.site-packages.scipy.integrate',
              'venv.lib.python3.6.site-packages.scipy.integrate._ivp',
              'venv.lib.python3.6.site-packages.scipy.integrate.tests',
              'venv.lib.python3.6.site-packages.scipy.interpolate',
              'venv.lib.python3.6.site-packages.scipy.interpolate.tests',
              'venv.lib.python3.6.site-packages.scipy._build_utils', 'venv.lib.python3.6.site-packages.future',
              'venv.lib.python3.6.site-packages.future.moves', 'venv.lib.python3.6.site-packages.future.moves.dbm',
              'venv.lib.python3.6.site-packages.future.moves.html',
              'venv.lib.python3.6.site-packages.future.moves.http',
              'venv.lib.python3.6.site-packages.future.moves.test',
              'venv.lib.python3.6.site-packages.future.moves.urllib',
              'venv.lib.python3.6.site-packages.future.moves.xmlrpc',
              'venv.lib.python3.6.site-packages.future.moves.tkinter', 'venv.lib.python3.6.site-packages.future.tests',
              'venv.lib.python3.6.site-packages.future.types', 'venv.lib.python3.6.site-packages.future.utils',
              'venv.lib.python3.6.site-packages.future.builtins', 'venv.lib.python3.6.site-packages.future.backports',
              'venv.lib.python3.6.site-packages.future.backports.html',
              'venv.lib.python3.6.site-packages.future.backports.http',
              'venv.lib.python3.6.site-packages.future.backports.test',
              'venv.lib.python3.6.site-packages.future.backports.email',
              'venv.lib.python3.6.site-packages.future.backports.email.mime',
              'venv.lib.python3.6.site-packages.future.backports.urllib',
              'venv.lib.python3.6.site-packages.future.backports.xmlrpc',
              'venv.lib.python3.6.site-packages.future.standard_library',
              'venv.lib.python3.6.site-packages.google.protobuf',
              'venv.lib.python3.6.site-packages.google.protobuf.util',
              'venv.lib.python3.6.site-packages.google.protobuf.pyext',
              'venv.lib.python3.6.site-packages.google.protobuf.compiler',
              'venv.lib.python3.6.site-packages.google.protobuf.internal',
              'venv.lib.python3.6.site-packages.google.protobuf.internal.import_test_package',
              'venv.lib.python3.6.site-packages.gridfs', 'venv.lib.python3.6.site-packages.joblib',
              'venv.lib.python3.6.site-packages.joblib.test', 'venv.lib.python3.6.site-packages.joblib.test.data',
              'venv.lib.python3.6.site-packages.joblib.externals',
              'venv.lib.python3.6.site-packages.joblib.externals.loky',
              'venv.lib.python3.6.site-packages.joblib.externals.loky.backend',
              'venv.lib.python3.6.site-packages.joblib.externals.cloudpickle',
              'venv.lib.python3.6.site-packages.pandas', 'venv.lib.python3.6.site-packages.pandas.io',
              'venv.lib.python3.6.site-packages.pandas.io.sas', 'venv.lib.python3.6.site-packages.pandas.io.json',
              'venv.lib.python3.6.site-packages.pandas.io.formats',
              'venv.lib.python3.6.site-packages.pandas.io.msgpack',
              'venv.lib.python3.6.site-packages.pandas.io.clipboard', 'venv.lib.python3.6.site-packages.pandas.api',
              'venv.lib.python3.6.site-packages.pandas.api.types',
              'venv.lib.python3.6.site-packages.pandas.api.extensions', 'venv.lib.python3.6.site-packages.pandas.core',
              'venv.lib.python3.6.site-packages.pandas.core.util', 'venv.lib.python3.6.site-packages.pandas.core.tools',
              'venv.lib.python3.6.site-packages.pandas.core.arrays',
              'venv.lib.python3.6.site-packages.pandas.core.dtypes',
              'venv.lib.python3.6.site-packages.pandas.core.sparse',
              'venv.lib.python3.6.site-packages.pandas.core.groupby',
              'venv.lib.python3.6.site-packages.pandas.core.indexes',
              'venv.lib.python3.6.site-packages.pandas.core.reshape',
              'venv.lib.python3.6.site-packages.pandas.core.computation',
              'venv.lib.python3.6.site-packages.pandas.util', 'venv.lib.python3.6.site-packages.pandas._libs',
              'venv.lib.python3.6.site-packages.pandas._libs.tslibs', 'venv.lib.python3.6.site-packages.pandas.tests',
              'venv.lib.python3.6.site-packages.pandas.tests.io',
              'venv.lib.python3.6.site-packages.pandas.tests.io.sas',
              'venv.lib.python3.6.site-packages.pandas.tests.io.json',
              'venv.lib.python3.6.site-packages.pandas.tests.io.parser',
              'venv.lib.python3.6.site-packages.pandas.tests.io.formats',
              'venv.lib.python3.6.site-packages.pandas.tests.io.msgpack',
              'venv.lib.python3.6.site-packages.pandas.tests.api', 'venv.lib.python3.6.site-packages.pandas.tests.util',
              'venv.lib.python3.6.site-packages.pandas.tests.frame',
              'venv.lib.python3.6.site-packages.pandas.tests.tools',
              'venv.lib.python3.6.site-packages.pandas.tests.dtypes',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.period',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.interval',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.timedelta',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.timestamp',
              'venv.lib.python3.6.site-packages.pandas.tests.series',
              'venv.lib.python3.6.site-packages.pandas.tests.series.indexing',
              'venv.lib.python3.6.site-packages.pandas.tests.sparse',
              'venv.lib.python3.6.site-packages.pandas.tests.sparse.frame',
              'venv.lib.python3.6.site-packages.pandas.tests.sparse.series',
              'venv.lib.python3.6.site-packages.pandas.tests.tslibs',
              'venv.lib.python3.6.site-packages.pandas.tests.generic',
              'venv.lib.python3.6.site-packages.pandas.tests.groupby',
              'venv.lib.python3.6.site-packages.pandas.tests.groupby.aggregate',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.period',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.interval',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.datetimes',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.timedeltas',
              'venv.lib.python3.6.site-packages.pandas.tests.reshape',
              'venv.lib.python3.6.site-packages.pandas.tests.reshape.merge',
              'venv.lib.python3.6.site-packages.pandas.tests.tseries',
              'venv.lib.python3.6.site-packages.pandas.tests.tseries.offsets',
              'venv.lib.python3.6.site-packages.pandas.tests.indexing',
              'venv.lib.python3.6.site-packages.pandas.tests.indexing.interval',
              'venv.lib.python3.6.site-packages.pandas.tests.plotting',
              'venv.lib.python3.6.site-packages.pandas.tests.extension',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.base',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.json',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.decimal',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.category',
              'venv.lib.python3.6.site-packages.pandas.tests.internals',
              'venv.lib.python3.6.site-packages.pandas.tests.categorical',
              'venv.lib.python3.6.site-packages.pandas.tests.computation',
              'venv.lib.python3.6.site-packages.pandas.tools', 'venv.lib.python3.6.site-packages.pandas.types',
              'venv.lib.python3.6.site-packages.pandas.compat', 'venv.lib.python3.6.site-packages.pandas.compat.numpy',
              'venv.lib.python3.6.site-packages.pandas.errors', 'venv.lib.python3.6.site-packages.pandas.formats',
              'venv.lib.python3.6.site-packages.pandas.tseries', 'venv.lib.python3.6.site-packages.pandas.plotting',
              'venv.lib.python3.6.site-packages.pandas.computation', 'venv.lib.python3.6.site-packages.certifi',
              'venv.lib.python3.6.site-packages.chardet', 'venv.lib.python3.6.site-packages.chardet.cli',
              'venv.lib.python3.6.site-packages.pymongo', 'venv.lib.python3.6.site-packages.sklearn',
              'venv.lib.python3.6.site-packages.sklearn.svm', 'venv.lib.python3.6.site-packages.sklearn.svm.tests',
              'venv.lib.python3.6.site-packages.sklearn.tree', 'venv.lib.python3.6.site-packages.sklearn.tree.tests',
              'venv.lib.python3.6.site-packages.sklearn.tests', 'venv.lib.python3.6.site-packages.sklearn.utils',
              'venv.lib.python3.6.site-packages.sklearn.utils.tests',
              'venv.lib.python3.6.site-packages.sklearn.utils.sparsetools',
              'venv.lib.python3.6.site-packages.sklearn.utils.sparsetools.tests',
              'venv.lib.python3.6.site-packages.sklearn.cluster',
              'venv.lib.python3.6.site-packages.sklearn.cluster.tests',
              'venv.lib.python3.6.site-packages.sklearn.metrics',
              'venv.lib.python3.6.site-packages.sklearn.metrics.tests',
              'venv.lib.python3.6.site-packages.sklearn.metrics.cluster',
              'venv.lib.python3.6.site-packages.sklearn.metrics.cluster.tests',
              'venv.lib.python3.6.site-packages.sklearn.mixture',
              'venv.lib.python3.6.site-packages.sklearn.mixture.tests',
              'venv.lib.python3.6.site-packages.sklearn.datasets',
              'venv.lib.python3.6.site-packages.sklearn.datasets.tests',
              'venv.lib.python3.6.site-packages.sklearn.ensemble',
              'venv.lib.python3.6.site-packages.sklearn.ensemble.tests',
              'venv.lib.python3.6.site-packages.sklearn.manifold',
              'venv.lib.python3.6.site-packages.sklearn.manifold.tests',
              'venv.lib.python3.6.site-packages.sklearn.externals',
              'venv.lib.python3.6.site-packages.sklearn.externals.joblib',
              'venv.lib.python3.6.site-packages.sklearn.neighbors',
              'venv.lib.python3.6.site-packages.sklearn.neighbors.tests',
              'venv.lib.python3.6.site-packages.sklearn.covariance',
              'venv.lib.python3.6.site-packages.sklearn.covariance.tests',
              'venv.lib.python3.6.site-packages.sklearn._build_utils',
              'venv.lib.python3.6.site-packages.sklearn.linear_model',
              'venv.lib.python3.6.site-packages.sklearn.linear_model.tests',
              'venv.lib.python3.6.site-packages.sklearn.__check_build',
              'venv.lib.python3.6.site-packages.sklearn.decomposition',
              'venv.lib.python3.6.site-packages.sklearn.decomposition.tests',
              'venv.lib.python3.6.site-packages.sklearn.preprocessing',
              'venv.lib.python3.6.site-packages.sklearn.preprocessing.tests',
              'venv.lib.python3.6.site-packages.sklearn.neural_network',
              'venv.lib.python3.6.site-packages.sklearn.neural_network.tests',
              'venv.lib.python3.6.site-packages.sklearn.model_selection',
              'venv.lib.python3.6.site-packages.sklearn.model_selection.tests',
              'venv.lib.python3.6.site-packages.sklearn.semi_supervised',
              'venv.lib.python3.6.site-packages.sklearn.semi_supervised.tests',
              'venv.lib.python3.6.site-packages.sklearn.gaussian_process',
              'venv.lib.python3.6.site-packages.sklearn.gaussian_process.tests',
              'venv.lib.python3.6.site-packages.sklearn.feature_selection',
              'venv.lib.python3.6.site-packages.sklearn.feature_selection.tests',
              'venv.lib.python3.6.site-packages.sklearn.feature_extraction',
              'venv.lib.python3.6.site-packages.sklearn.feature_extraction.tests',
              'venv.lib.python3.6.site-packages.sklearn.cross_decomposition',
              'venv.lib.python3.6.site-packages.sklearn.cross_decomposition.tests',
              'venv.lib.python3.6.site-packages.urllib3', 'venv.lib.python3.6.site-packages.urllib3.util',
              'venv.lib.python3.6.site-packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.dateutil', 'venv.lib.python3.6.site-packages.dateutil.tz',
              'venv.lib.python3.6.site-packages.dateutil.parser', 'venv.lib.python3.6.site-packages.dateutil.zoneinfo',
              'venv.lib.python3.6.site-packages.oauthlib', 'venv.lib.python3.6.site-packages.oauthlib.oauth1',
              'venv.lib.python3.6.site-packages.oauthlib.oauth1.rfc5849',
              'venv.lib.python3.6.site-packages.oauthlib.oauth1.rfc5849.endpoints',
              'venv.lib.python3.6.site-packages.oauthlib.oauth2',
              'venv.lib.python3.6.site-packages.oauthlib.oauth2.rfc6749',
              'venv.lib.python3.6.site-packages.oauthlib.oauth2.rfc6749.clients',
              'venv.lib.python3.6.site-packages.oauthlib.oauth2.rfc6749.endpoints',
              'venv.lib.python3.6.site-packages.oauthlib.oauth2.rfc6749.grant_types',
              'venv.lib.python3.6.site-packages.requests', 'venv.lib.python3.6.site-packages.selenium',
              'venv.lib.python3.6.site-packages.selenium.common', 'venv.lib.python3.6.site-packages.selenium.webdriver',
              'venv.lib.python3.6.site-packages.selenium.webdriver.ie',
              'venv.lib.python3.6.site-packages.selenium.webdriver.edge',
              'venv.lib.python3.6.site-packages.selenium.webdriver.opera',
              'venv.lib.python3.6.site-packages.selenium.webdriver.chrome',
              'venv.lib.python3.6.site-packages.selenium.webdriver.common',
              'venv.lib.python3.6.site-packages.selenium.webdriver.common.html5',
              'venv.lib.python3.6.site-packages.selenium.webdriver.common.actions',
              'venv.lib.python3.6.site-packages.selenium.webdriver.remote',
              'venv.lib.python3.6.site-packages.selenium.webdriver.safari',
              'venv.lib.python3.6.site-packages.selenium.webdriver.android',
              'venv.lib.python3.6.site-packages.selenium.webdriver.firefox',
              'venv.lib.python3.6.site-packages.selenium.webdriver.support',
              'venv.lib.python3.6.site-packages.selenium.webdriver.phantomjs',
              'venv.lib.python3.6.site-packages.selenium.webdriver.webkitgtk',
              'venv.lib.python3.6.site-packages.selenium.webdriver.blackberry',
              'venv.lib.python3.6.site-packages.surprise', 'venv.lib.python3.6.site-packages.surprise.model_selection',
              'venv.lib.python3.6.site-packages.surprise.prediction_algorithms',
              'venv.lib.python3.6.site-packages.backports.configparser', 'venv.lib.python3.6.site-packages.flickrapi',
              'venv.lib.python3.6.site-packages.hyperframe', 'venv.lib.python3.6.site-packages.jsonschema',
              'venv.lib.python3.6.site-packages.jsonschema.tests', 'venv.lib.python3.6.site-packages.setuptools',
              'venv.lib.python3.6.site-packages.setuptools.extern',
              'venv.lib.python3.6.site-packages.setuptools._vendor',
              'venv.lib.python3.6.site-packages.setuptools._vendor.packaging',
              'venv.lib.python3.6.site-packages.setuptools.command', 'venv.lib.python3.6.site-packages.googletrans',
              'venv.lib.python3.6.site-packages.libfuturize', 'venv.lib.python3.6.site-packages.libfuturize.fixes',
              'venv.lib.python3.6.site-packages.libpasteurize', 'venv.lib.python3.6.site-packages.libpasteurize.fixes',
              'venv.lib.python3.6.site-packages.pkg_resources', 'venv.lib.python3.6.site-packages.pkg_resources.extern',
              'venv.lib.python3.6.site-packages.pkg_resources._vendor',
              'venv.lib.python3.6.site-packages.pkg_resources._vendor.packaging',
              'venv.lib.python3.6.site-packages.requests_oauthlib',
              'venv.lib.python3.6.site-packages.requests_oauthlib.compliance_fixes',
              'venv.lib.python3.6.site-packages.requests_toolbelt',
              'venv.lib.python3.6.site-packages.requests_toolbelt.auth',
              'venv.lib.python3.6.site-packages.requests_toolbelt.utils',
              'venv.lib.python3.6.site-packages.requests_toolbelt.cookies',
              'venv.lib.python3.6.site-packages.requests_toolbelt.adapters',
              'venv.lib.python3.6.site-packages.requests_toolbelt.threaded',
              'venv.lib.python3.6.site-packages.requests_toolbelt.multipart',
              'venv.lib.python3.6.site-packages.requests_toolbelt.downloadutils'],
    url='',
    license='',
    author='mrsmabo93',
    author_email='',
    description=''
)
